name: Update Last Updated

on:
  push:
    branches:
      - main

jobs:
  update-last-updated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update Last Updated
        run: |
          const fs = require('fs');
          const fetch = require('node-fetch');

          fetch('https://api.github.com/repos/halfseal/halfseal.github.io/commits?per_page=1')
            .then(response => response.json())
            .then(data => {
              const lastCommitDate = new Date(data[0].commit.author.date);
              const options = { year: 'numeric', month: 'long', day: 'numeric' };
              const updatedText = `<h6>Last Updated: ${lastCommitDate.toLocaleDateString(undefined, options)}</h6>`;
              const htmlFilePath = '/index.html';
              let htmlContent = fs.readFileSync(htmlFilePath, 'utf8');
              htmlContent = htmlContent.replace(/<h6>Last Updated: .*?<\/h6>/, updatedText);
              fs.writeFileSync(htmlFilePath, htmlContent, 'utf8');
            })
            .catch(error => {
              console.error('Error fetching last commit data:', error);
            });
